

using Microsoft.Extensions.AI;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using TimShaw.VoiceBox.Core;
using TimShaw.VoiceBox.Data;
using TimShaw.VoiceBox.Generics;
using UnityEditor;
using UnityEngine;

namespace TimShaw.VoiceBox.Components
{
    /// <summary>
    /// An individual chat service manager. Useful if working with multiple different chat services.
    /// </summary>
    public class ChatManager : MonoBehaviour
    {
        private readonly CancellationTokenSource internalCancellationTokenSource = new CancellationTokenSource();

        /// <summary>
        /// Path to the api keys json file.
        /// </summary>
        [Tooltip("Path to the api keys json file.")]
        [SerializeField] public string apiKeysJsonPath = "";

        /// <summary>
        /// Configuration asset for the Chat service (e.g., <see cref="GeminiServiceConfig"/>).
        /// </summary>
        [Tooltip("Configuration asset for the chat service (e.g., GeminiConfig, ChatGPTConfig).")]
        [SerializeField] public GenericChatServiceConfig chatServiceConfig;

        private IChatService _chatService;
        /// <summary>
        /// The Chat service generated by the <see cref="ServiceFactory"/>
        /// </summary>
        public IChatService ChatService { get => _chatService; set => _chatService = value; }
#if UNITY_EDITOR
        [MenuItem("GameObject/VoiceBox/Managers/Chat Manager", false, 11)]
#endif
        static void CreateAudioStreamerObj()
        {
            var obj = new GameObject("ChatManager");
            obj.AddComponent<ChatManager>();
        }

        /// <summary>
        /// 
        /// </summary>
        public void Awake()
        {
            LoadAPIKey(apiKeysJsonPath.Length > 0 ? apiKeysJsonPath : Application.dataPath + "/keys.json");
            ChatService = ServiceFactory.CreateChatService(chatServiceConfig);
        }

        /// <summary>
        /// Cancels all running tasks and unloads API key when the application quits.
        /// </summary>
        private void OnDestroy()
        {
            internalCancellationTokenSource.Cancel();
            chatServiceConfig.apiKey = "";
        }

        /// <summary>
        /// Loads API keys from a JSON file and applies them to the service configurations.
        /// </summary>
        /// <param name="keysFile">The path to the JSON file containing the API keys.</param>
        public void LoadAPIKey(string keysFile)
        {
            string jsonContent = File.ReadAllText(keysFile);
            var apiKeys = JsonSerializer.Deserialize<Dictionary<string, string>>(jsonContent);

            if (chatServiceConfig && chatServiceConfig.apiKeyJSONString.Length > 0)
                chatServiceConfig.apiKey = apiKeys[chatServiceConfig.apiKeyJSONString];
            else
                Debug.LogWarning("Chat service config does not define an apiKeyJSONString");
        }

        /// <summary>
        /// Sends a conversation history to the configured chat service.
        /// </summary>
        /// <param name="messageHistory">A list of chat messages representing the conversation history.</param>
        /// <param name="onSuccess">Callback invoked when the message is successfully sent, returning the response.</param>
        /// <param name="onError">Callback invoked when an error occurs.</param>
        /// <param name="options">(Optional) Request-level settings.</param>
        /// <param name="token"></param>
        public void SendChatMessage(
            List<ChatUtils.VoiceBoxChatMessage> messageHistory,
            Action<ChatMessage> onSuccess,
            Action<string> onError,
            ChatUtils.VoiceBoxChatCompletionOptions options = null,
            CancellationToken token = default)
        {
            if (ChatService == null)
            {
                onError?.Invoke("Chat service is not initialized. Check AIManager configuration.");
                return;
            }

            token = CancellationTokenSource.CreateLinkedTokenSource(token, internalCancellationTokenSource.Token).Token;

            Task.Run(() => ChatService.SendMessage(messageHistory, onSuccess, onError, options, token));
        }

        /// <summary>
        /// Sends a message to the Chat service and streams the response.
        /// </summary>
        /// <param name="messageHistory">The history of messages in the conversation.</param>
        /// <param name="onChunkReceived">Callback invoked when a chunk of the response is received.</param>
        /// <param name="onComplete">Callback invoked when the response is complete.</param>
        /// <param name="onError">Callback invoked when an error occurs.</param>
        /// <param name="options">(Optional) Request-level settings.</param>
        /// <param name="token"></param>
        public void StreamChatMessage(
            List<ChatUtils.VoiceBoxChatMessage> messageHistory,
            Action<ChatResponseUpdate> onChunkReceived,
            Action onComplete,
            Action<string> onError,
            ChatUtils.VoiceBoxChatCompletionOptions options = null,
            CancellationToken token = default
        )
        {
            if (ChatService == null)
            {
                onError?.Invoke("Chat service is not initialized. Check AIManager configuration.");
                return;
            }

            token = CancellationTokenSource.CreateLinkedTokenSource(token, internalCancellationTokenSource.Token).Token;

            Task.Run(() => ChatService.SendMessageStream(messageHistory, onChunkReceived, onComplete, onError, options, token));
        }
    }
}