

using Microsoft.Extensions.AI;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using TimShaw.VoiceBox.Core;
using TimShaw.VoiceBox.Data;
using TimShaw.VoiceBox.Generics;
using UnityEditor;
using UnityEngine;

namespace TimShaw.VoiceBox.Components
{
    /// <summary>
    /// An individual chat service manager. Useful if working with multiple different chat services.
    /// </summary>
    public class ChatManager : MonoBehaviour
    {
        private readonly CancellationTokenSource internalCancellationTokenSource = new CancellationTokenSource();

        /// <summary>
        /// Path to the api keys json file.
        /// </summary>
        [Tooltip("Path to the api keys json file.")]
        [SerializeField] public string apiKeysJsonPath = "";

        /// <summary>
        /// Configuration asset for the Chat service (e.g., <see cref="GeminiServiceConfig"/>).
        /// </summary>
        [Tooltip("Configuration asset for the chat service (e.g., GeminiConfig, ChatGPTConfig).")]
        [SerializeField] public GenericChatServiceConfig chatServiceConfig;

        private IChatService _chatService;
        /// <summary>
        /// The Chat service generated by the <see cref="ServiceFactory"/>
        /// </summary>
        public IChatService ChatService { get => _chatService; set => _chatService = value; }
#if UNITY_EDITOR
        [MenuItem("GameObject/VoiceBox/Managers/Chat Manager", false, 11)]
#endif
        static void CreateAudioStreamerObj()
        {
            var obj = new GameObject("ChatManager");
            obj.AddComponent<ChatManager>();
        }

        /// <summary>
        /// 
        /// </summary>
        public void Awake()
        {
            LoadAPIKey(apiKeysJsonPath.Length > 0 ? apiKeysJsonPath : Application.dataPath + "/keys.json");
            ChatService = ServiceFactory.CreateChatService(chatServiceConfig);
        }

        /// <summary>
        /// Cancels all running tasks and unloads API key when the application quits.
        /// </summary>
        private void OnDestroy()
        {
            internalCancellationTokenSource.Cancel();
            chatServiceConfig.apiKey = "";
        }

        /// <summary>
        /// Loads API keys from direct arguments, environment variables, or a JSON file (in that order of precedence)
        /// </summary>
        /// <param name="keysFile">Optional path to the JSON file with API keys.</param>
        /// <param name="chatKey">Optional, direct API key for the chat service.</param>
        /// <param name="sttKey">Optional, direct API key for the Speech-to-Text service.</param>
        /// <param name="ttsKey">Optional, direct API key for the Text-to-Speech service.</param>
        public void LoadAPIKey(string keysFile = null, string chatKey = null, string sttKey = null, string ttsKey = null)
        {
            // Load from JSON file if provided
            Dictionary<string, string> apiKeysFromFile = null;
            if (!string.IsNullOrEmpty(keysFile))
            {
                apiKeysFromFile = LoadKeysFromFile(keysFile);
            }

            if (chatServiceConfig != null)
            {
                chatServiceConfig.apiKey = GetApiKey(chatKey, chatServiceConfig.apiKeyJSONString, chatServiceConfig.apiKeyJSONString, apiKeysFromFile);
                if (string.IsNullOrEmpty(chatServiceConfig.apiKey))
                    Debug.LogWarning("Chat service API key not found.");
            }
        }

        /// <summary>
        /// Loads API keys from a JSON file.
        /// </summary>
        private Dictionary<string, string> LoadKeysFromFile(string keysFile)
        {
            try
            {
                string jsonContent = File.ReadAllText(keysFile);
                return JsonSerializer.Deserialize<Dictionary<string, string>>(jsonContent);
            }
            catch (FileNotFoundException)
            {
                Debug.LogWarning($"[AI Manager] API keys json file not found at: {keysFile}");
                return null;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[AI Manager] Error reading API keys file: {ex.Message}");
                return null;
            }
        }

        private string GetApiKey(string directKey, string envVar, string jsonKey, Dictionary<string, string> keysFromFile)
        {
            // 1. Direct parameter
            if (!string.IsNullOrEmpty(directKey))
            {
                return directKey;
            }

            // 2. Environment variable
            if (!string.IsNullOrEmpty(envVar))
            {
                string envValue = Environment.GetEnvironmentVariable(envVar, EnvironmentVariableTarget.User);
                if (!string.IsNullOrEmpty(envValue))
                {
                    return envValue;
                }
            }

            // 3. JSON file
            if (keysFromFile != null && !string.IsNullOrEmpty(jsonKey) && keysFromFile.ContainsKey(jsonKey))
            {
                return keysFromFile[jsonKey];
            }

            return null;
        }

        /// <summary>
        /// Sends a conversation history to the configured chat service.
        /// </summary>
        /// <param name="messageHistory">A list of chat messages representing the conversation history.</param>
        /// <param name="onSuccess">Callback invoked when the message is successfully sent, returning the response.</param>
        /// <param name="onError">Callback invoked when an error occurs.</param>
        /// <param name="options">(Optional) Request-level settings.</param>
        /// <param name="token"></param>
        public void SendChatMessage(
            List<ChatUtils.VoiceBoxChatMessage> messageHistory,
            Action<ChatMessage> onSuccess,
            Action<string> onError,
            ChatUtils.VoiceBoxChatCompletionOptions options = null,
            CancellationToken token = default)
        {
            if (ChatService == null)
            {
                onError?.Invoke("Chat service is not initialized. Check AIManager configuration.");
                return;
            }

            token = CancellationTokenSource.CreateLinkedTokenSource(token, internalCancellationTokenSource.Token).Token;

            Task.Run(() => ChatService.SendMessage(messageHistory, onSuccess, onError, options, token));
        }

        /// <summary>
        /// Sends a message to the Chat service and streams the response.
        /// </summary>
        /// <param name="messageHistory">The history of messages in the conversation.</param>
        /// <param name="onChunkReceived">Callback invoked when a chunk of the response is received.</param>
        /// <param name="onComplete">Callback invoked when the response is complete.</param>
        /// <param name="onError">Callback invoked when an error occurs.</param>
        /// <param name="options">(Optional) Request-level settings.</param>
        /// <param name="token"></param>
        public void StreamChatMessage(
            List<ChatUtils.VoiceBoxChatMessage> messageHistory,
            Action<ChatResponseUpdate> onChunkReceived,
            Action onComplete,
            Action<string> onError,
            ChatUtils.VoiceBoxChatCompletionOptions options = null,
            CancellationToken token = default
        )
        {
            if (ChatService == null)
            {
                onError?.Invoke("Chat service is not initialized. Check AIManager configuration.");
                return;
            }

            token = CancellationTokenSource.CreateLinkedTokenSource(token, internalCancellationTokenSource.Token).Token;

            Task.Run(() => ChatService.SendMessageStream(messageHistory, onChunkReceived, onComplete, onError, options, token));
        }
    }
}