

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using TimShaw.VoiceBox.Core;
using TimShaw.VoiceBox.Data;
using TimShaw.VoiceBox.Generics;
using UnityEditor;
using UnityEngine;

namespace TimShaw.VoiceBox.Components
{
    /// <summary>
    /// An individual TTS service manager. Useful if working with multiple different TTS services or voices.
    /// </summary>
    [RequireComponent(typeof(AudioStreamer))]
    public class TTSManager : MonoBehaviour
    {
        private CancellationTokenSource internalCancellationTokenSource = new CancellationTokenSource();

        /// <summary>
        /// Path to the api keys json file.
        /// </summary>
        [Tooltip("Path to the api keys json file (Optional).")]
        [SerializeField] public string apiKeysJsonPath = "";

        /// <summary>
        /// Configuration asset for the TTS service (e.g., <see cref="ElevenlabsTTSServiceConfig"/>).
        /// </summary>
        [Tooltip("Configuration asset for the TTS service (e.g., ElevenlabsConfig).")]
        [SerializeField] public GenericTTSServiceConfig textToSpeechConfig;

        private ITextToSpeechService _ttsService;
        /// <summary>
        /// The Text-To-Speech service generated by the <see cref="ServiceFactory"/>
        /// </summary>
        public ITextToSpeechService TextToSpeechService { get => _ttsService; set => _ttsService = value; }
#if UNITY_EDITOR
        [MenuItem("GameObject/VoiceBox/Managers/TTS Manager", false, 11)]
#endif
        static void CreateTTSManagerObj()
        {
            var obj = new GameObject("TTSManager");
            obj.AddComponent<TTSManager>();
        }

        /// <summary>
        /// 
        /// </summary>
        public void Awake()
        {
            if (apiKeysJsonPath.Length > 0)
                LoadAPIKey(apiKeysJsonPath);
            else
                LoadAPIKey();
            TextToSpeechService = ServiceFactory.CreateTtsService(textToSpeechConfig);
        }

        /// <summary>
        /// Unloads API key from config
        /// </summary>
        private void OnDestroy()
        {
            textToSpeechConfig.apiKey = "";
            internalCancellationTokenSource.Cancel();
        }

        /// <summary>
        /// Loads API keys from direct arguments, environment variables, or a JSON file (in that order of precedence)
        /// </summary>
        /// <param name="keysFile">Optional path to the JSON file with API keys.</param>
        /// <param name="ttsKey">Optional, direct API key for the Text-to-Speech service.</param>
        public void LoadAPIKey(string keysFile = null, string ttsKey = null)
        {
            // Load from JSON file if provided
            Dictionary<string, string> apiKeysFromFile = null;
            if (!string.IsNullOrEmpty(keysFile))
            {
                apiKeysFromFile = LoadKeysFromFile(keysFile);
            }

            if (textToSpeechConfig != null)
            {
                textToSpeechConfig.apiKey = GetApiKey(ttsKey, textToSpeechConfig.apiKeyJSONString, textToSpeechConfig.apiKeyJSONString, apiKeysFromFile);
                if (string.IsNullOrEmpty(textToSpeechConfig.apiKey))
                    Debug.LogWarning("[TTS Manager] TTS service API key not found.");
            }
        }

        /// <summary>
        /// Loads API keys from a JSON file.
        /// </summary>
        private Dictionary<string, string> LoadKeysFromFile(string keysFile)
        {
            try
            {
                string jsonContent = File.ReadAllText(keysFile);
                return JsonSerializer.Deserialize<Dictionary<string, string>>(jsonContent);
            }
            catch (FileNotFoundException)
            {
                Debug.LogWarning($"[TTS Manager] API keys json file not found at: {keysFile}");
                return null;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[TTS Manager] Error reading API keys file: {ex.Message}");
                return null;
            }
        }

        private string GetApiKey(string directKey, string envVar, string jsonKey, Dictionary<string, string> keysFromFile)
        {
            // 1. Direct parameter
            if (!string.IsNullOrEmpty(directKey))
            {
                return directKey;
            }

            // 2. Environment variable
            if (!string.IsNullOrEmpty(envVar))
            {
                string envValue = Environment.GetEnvironmentVariable(envVar, EnvironmentVariableTarget.User);
                if (!string.IsNullOrEmpty(envValue))
                {
                    return envValue;
                }
            }

            // 3. JSON file
            if (keysFromFile != null && !string.IsNullOrEmpty(jsonKey) && keysFromFile.ContainsKey(jsonKey))
            {
                return keysFromFile[jsonKey];
            }

            return null;
        }

        /// <summary>
        /// Generates a speech audio file from the given text prompt.
        /// </summary>
        /// <param name="prompt">The text to be converted to speech.</param>
        /// <param name="fileName">The name of the output audio file.</param>
        /// <param name="dir">The directory to save the audio file in.</param>
        /// <param name="onSuccess">Callback for when file is created. Should return the path to the file.</param>
        /// <param name="onError">Callback when an error ocurrs</param>
        /// <param name="token"></param>
        public void GenerateSpeechFileFromText(string prompt, string fileName, string dir, Action<string> onSuccess, Action<string> onError, CancellationToken token = default)
        {
            Task.Run(() => TextToSpeechService.RequestAudioFile(prompt, fileName, dir, onSuccess, onError, token));
        }

        /// <summary>
        /// Generates an AudioClip from the given text prompt.
        /// </summary>
        /// <param name="prompt">The text to be converted to speech.</param>
        /// <param name="onSuccess">Callback invoked with the generated AudioClip on success.</param>
        /// <param name="onError">Callback invoked with an error message on failure.</param>
        public async void GenerateSpeechAudioClipFromText(
            string prompt,
            Action<AudioClip> onSuccess,
            Action<string> onError)
        {
            try
            {
                AudioClip audioClip = await TextToSpeechService.RequestAudioClip(prompt);
                onSuccess?.Invoke(audioClip);
            }
            catch (Exception e)
            {
                onError?.Invoke($"Failed to generate speech: {e.Message}");
            }
        }

        /// <summary>
        /// Requests and streams audio from a text prompt to an attached AudioSource.
        /// </summary>
        /// <param name="prompt">The text to be converted to speech.</param>
        public void RequestAudioAndStream(string prompt)
        {
            AudioStreamer audioStreamer = GetComponent<AudioStreamer>();
            if (audioStreamer)
            {
                audioStreamer.InitStreaming(TextToSpeechService);
                audioStreamer.ConnectAndStream(prompt, TextToSpeechService, true, internalCancellationTokenSource.Token);
            }
            else
                Debug.LogError("[TTS Manager] Manager object does not have an AudioStreamer attached to it!");

        }

        /// <summary>
        /// Requests and streams audio from a text prompt to an attached AudioSource.
        /// </summary>
        /// <param name="prompt">The text to be converted to speech.</param>
        public void RequestAudioAndStream(string promptChunk, bool isFinalSegment)
        {
            AudioStreamer audioStreamer = GetComponent<AudioStreamer>();
            if (audioStreamer)
            {
                audioStreamer.InitStreaming(TextToSpeechService);
                audioStreamer.ConnectAndStream(promptChunk, TextToSpeechService, isFinalSegment, internalCancellationTokenSource.Token);
            }
            else
                Debug.LogError("[TTS Manager] Manager object does not have an AudioStreamer attached to it!");

        }

        /// <summary>
        /// Requests and streams audio from a text prompt to an AudioSource.
        /// </summary>
        /// <param name="prompt">The text to be converted to speech.</param>
        /// <param name="audioStreamer">The AudioSource to stream the audio to.</param>
        public void RequestAudioAndStream(string prompt, AudioStreamer audioStreamer)
        {
            if (audioStreamer)
            {
                audioStreamer.InitStreaming(TextToSpeechService);
                audioStreamer.ConnectAndStream(prompt, TextToSpeechService, true, internalCancellationTokenSource.Token);
            }
            else
                Debug.LogError("[TTS Manager] Audio Streamer is null");
        }

        /// <summary>
        /// Requests and streams audio from a text prompt to an attached AudioSource.
        /// </summary>
        /// <param name="prompt">The text to be converted to speech.</param>
        public void RequestAudioAndStream(string promptChunk, bool isFinalSegment, AudioStreamer audioStreamer)
        {
            if (audioStreamer)
            {
                audioStreamer.InitStreaming(TextToSpeechService);
                audioStreamer.ConnectAndStream(promptChunk, TextToSpeechService, isFinalSegment, internalCancellationTokenSource.Token);
            }
            else
                Debug.LogError("[TTS Manager] Audio Streamer is null");

        }

        /// <summary>
        /// Creates a voice clone named <paramref name="voiceName"/> given a provided list of audio files.
        /// </summary>
        /// <param name="filePaths">List of file paths to upload.</param>
        /// <param name="voiceName">The name of the voice.</param>
        /// <param name="description">Optional description for the voice.</param>
        /// <param name="removeBackgroundNoise">If true, the API will attempt to clean up audio artifacts.</param>
        /// <returns>The VoiceID of the cloned voice.</returns>
        public async Task<string> CloneVoiceAndGetVoiceIDAsync(
            AudioFileSource filePaths,
            string voiceName,
            string description = "",
            bool removeBackgroundNoise = false)
        {
            return await TextToSpeechService.CloneVoiceAndGetVoiceIDAsync(filePaths.Paths, voiceName, description, removeBackgroundNoise);
        }

        /// <summary>
        /// Creates a voice clone named <paramref name="voiceName"/> given a provided <paramref name="audioDataList"/>.
        /// </summary>
        /// <param name="audioDataList">List of raw audio byte arrays.</param>
        /// <param name="voiceName">The name of the voice.</param>
        /// <param name="description">Optional description for the voice.</param>
        /// <param name="removeBackgroundNoise">If true, the API will attempt to clean up audio artifacts.</param>
        /// <param name="mediaType">The media type the audioData is (e.g., mpeg, wav).</param>
        /// <returns>The VoiceID of the cloned voice.</returns>
        public async Task<string> CloneVoiceAndGetVoiceIDAsync(
            AudioDataSource audioDataList,
            string voiceName,
            string description = "",
            bool removeBackgroundNoise = false,
            string mediaType = "mpeg")
        {
            return await TextToSpeechService.CloneVoiceAndGetVoiceIDAsync(audioDataList.Data, voiceName, description, removeBackgroundNoise, mediaType);
        }
    }
}