using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using UnityEngine;

namespace TimShaw.VoiceBox.Core
{
    /// <summary>
    /// Defines the role of the entity sending a message in a conversation.
    /// This is used by models to understand the context of the conversation.
    /// </summary>
    [Serializable]
    public enum MessageRole
    {
        /// <summary>
        /// A message from the system, providing instructions or context to the model.
        /// </summary>
        System,
        /// <summary>
        /// A message originating from the end-user.
        /// </summary>
        User,
        /// <summary>
        /// A message generated by the AI model.
        /// </summary>
        Model
    }

    /// <summary>
    /// Represents a single message in a conversation history.
    /// </summary>
    [Serializable]
    public struct ChatMessage
    {
        /// <summary>
        /// The role of the message sender (System, User, or Model).
        /// </summary>
        public MessageRole Role;
        /// <summary>
        /// The text content of the message.
        /// </summary>
        [TextArea(3, 10)]
        public string Content;

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatMessage"/> struct.
        /// </summary>
        /// <param name="role">The role of the message sender.</param>
        /// <param name="content">The text content of the message.</param>
        public ChatMessage(MessageRole role, string content)
        {
            Role = role;
            Content = content;
        }
    }

    /// <summary>
    /// Defines the contract for any chat service (e.g., Gemini, ChatGPT, etc.).
    /// This interface provides a standardized way to send messages and receive responses,
    /// abstracting away the specific details of each API.
    /// </summary>
    public interface IChatService
    {
        /// <summary>
        /// Initializes the service with the necessary configuration.
        /// This should be called before any other methods.
        /// </summary>
        /// <param name="config">A ScriptableObject containing API keys, model names, and other settings.</param>
        void Initialize(ScriptableObject config);

        /// <summary>
        /// Sends a complete conversation history to the chat service and waits for a single, complete response.
        /// </summary>
        /// <param name="messageHistory">The list of messages representing the conversation so far.</param>
        /// <param name="onSuccess">Callback invoked when a successful response is received. The ChatMessage will have the 'Model' role.</param>
        /// <param name="onError">Callback invoked when an error occurs, providing an error message.</param>
        Task SendMessage(
            List<ChatMessage> messageHistory,
            Action<ChatMessage> onSuccess,
            Action<string> onError
        );

        /// <summary>
        /// Sends a conversation history and streams the response back in chunks.
        /// This is useful for creating a "typing" effect and reducing perceived latency.
        /// </summary>
        /// <param name="messageHistory">The list of messages representing the conversation so far.</param>
        /// <param name="onChunkReceived">Callback invoked for each partial chunk of the response received from the stream.</param>
        /// <param name="onComplete">Callback invoked when the entire stream has finished.</param>
        /// <param name="onError">Callback invoked if an error occurs during the streaming process.</param>
        Task SendMessageStream(
            List<ChatMessage> messageHistory,
            Action<string> onChunkReceived,
            Action onComplete,
            Action<string> onError
        )
        {
            return null;
        }
    }
}